"""Pydantic v2 response models for the AlphaAI API."""

from __future__ import annotations

from .enums import (
    Actionability,
    ActionabilityLike,
    CategoryLike,
    Confidence,
    ConfidenceLike,
    NewsCategory,
    Sentiment,
    SentimentLike,
)
from .news import (
    AITradingInsights,
    AlternativePerspectives,
    EnrichedArticle,
    ImpactAnalysis,
    IndirectMarketEffects,
    InsiderEvent,
    KeyEntity,
    NewsContextEnhancement,
    NewsPagination,
    NewsTradingValue,
    OriginalArticle,
    RichNewsArticle,
    TickerAnalysis,
    Topic,
)
from .symbols import (
    DailySentimentBucket,
    EarningsRead,
    EarningsReport,
    Guidance,
    KeyMetric,
    LatestEarningsPointer,
    Quote,
    Segment,
    Symbol,
    TickerEarningsHistory,
    TickerInsiderSummary,
    TickerSentimentSummary,
    TopInsider,
    VsPriorGuidance,
)

# Friendlier alias for the news page returned by list/insider endpoints.
NewsPage = NewsPagination

__all__ = [
    "AITradingInsights",
    "Actionability",
    "ActionabilityLike",
    "AlternativePerspectives",
    "CategoryLike",
    "Confidence",
    "ConfidenceLike",
    "DailySentimentBucket",
    "EarningsRead",
    "EarningsReport",
    "EnrichedArticle",
    "Guidance",
    "ImpactAnalysis",
    "IndirectMarketEffects",
    "KeyEntity",
    "KeyMetric",
    "LatestEarningsPointer",
    "NewsCategory",
    "NewsContextEnhancement",
    "NewsPage",
    "NewsPagination",
    "NewsTradingValue",
    "OriginalArticle",
    "InsiderEvent",
    "Quote",
    "RichNewsArticle",
    "Segment",
    "Sentiment",
    "SentimentLike",
    "Symbol",
    "TickerAnalysis",
    "TickerEarningsHistory",
    "TickerInsiderSummary",
    "TickerSentimentSummary",
    "TopInsider",
    "Topic",
    "VsPriorGuidance",
]
